using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Shiny.Mediator.SourceGenerators;

internal static class OpenApiPolymorphicConverterGenerator
{
    internal static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    internal static void Generate(SourceProductionContext context, string ns, OpenApiPolymorphicBase model, bool useInternal)
    {
        var name = model.Name;
        var tag = Literal(model.Discriminator);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine(Constants.GeneratedCodeAttributeString);
        sb.AppendLine($"{(useInternal ? "internal" : "public")} sealed class {name}JsonConverter : global::System.Text.Json.Serialization.JsonConverter<{name}>");
        sb.AppendLine("{");
        sb.AppendLine("    public override bool HandleNull => true;");
        sb.AppendLine();
        sb.AppendLine($"    public override {name} Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (reader.TokenType != global::System.Text.Json.JsonTokenType.StartObject)");
        sb.AppendLine($"            throw new global::System.Text.Json.JsonException({Literal($"Expected a non-null {name} object.")});");
        sb.AppendLine("        using var document = global::System.Text.Json.JsonDocument.ParseValue(ref reader);");
        sb.AppendLine("        string? discriminator = null;");
        sb.AppendLine("        var found = false;");
        sb.AppendLine("        foreach (var property in document.RootElement.EnumerateObject())");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (!property.NameEquals({tag})) continue;");
        sb.AppendLine("            if (found || property.Value.ValueKind != global::System.Text.Json.JsonValueKind.String)");
        sb.AppendLine($"                throw new global::System.Text.Json.JsonException({Literal($"{name} requires exactly one string discriminator '{model.Discriminator}'.")});");
        sb.AppendLine("            found = true;");
        sb.AppendLine("            discriminator = property.Value.GetString();");
        sb.AppendLine("        }");
        sb.AppendLine("        return discriminator switch");
        sb.AppendLine("        {");
        foreach (var variant in model.Variants)
            sb.AppendLine($"            {Literal(variant.Key)} => global::System.Text.Json.JsonSerializer.Deserialize(document.RootElement, (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<{variant.Value}>)options.GetTypeInfo(typeof({variant.Value})))!,");
        sb.AppendLine($"            _ => throw new global::System.Text.Json.JsonException({Literal($"Missing or unknown discriminator '{model.Discriminator}' for {name}.")})");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public override void Write(global::System.Text.Json.Utf8JsonWriter writer, {name} value, global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (value)");
        sb.AppendLine("        {");
        foreach (var variant in model.Variants)
        {
            sb.AppendLine($"            case {variant.Value} concrete:");
            sb.AppendLine($"                global::System.Text.Json.JsonSerializer.Serialize(writer, concrete, (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<{variant.Value}>)options.GetTypeInfo(typeof({variant.Value})));");
            sb.AppendLine("                return;");
        }
        sb.AppendLine("            default:");
        sb.AppendLine($"                throw new global::System.Text.Json.JsonException({Literal($"Unsupported or null {name} variant.")});");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        context.AddSource($"{ns}.{name}JsonConverter.g.cs", sb.ToString());
    }
}
